---

- name: Include variables suitable to our OS Family
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks suitable to our OS Family
  include: "{{ ansible_os_family }}.yml"

- name: Replace custom clamd.conf
  template:
    dest: /etc/clamav/clamd.conf
    src: clamd.conf.j2
    owner: clamav
    group: root
    mode: 0440
  notify: Restart ClamAV

- name: Replace custom freshclam.conf
  template:
    dest: /etc/clamav/freshclam.conf
    src: freshclam.conf.j2
    owner: clamav
    group: root
    mode: 0440
  notify: Restart Freshclam

- name: Freshclam Status
  copy:
    src: freshclam_status.sh
    dest: /usr/local/bin/freshclam_status
    owner: root
    group: root
    mode: 0755

- name: Start clamav daemon
  service:
    name: clamav-daemon
    state: started
    enabled: yes

- name: Start freshclam daemon
  service:
    name: clamav-freshclam
    state: started
    enabled: yes

- shell: "/usr/local/bin/freshclam_status"
  register: result
  until: result.stdout.find("OK") != -1
  retries: 10
  delay: 20
