---

- name: Restart ClamAV
  service:
    name: "{{ clamav_daemon }}"
    state: restarted

- name: Restart Freshclam
  service:
    name: "{{ clamav_update }}"
    state: restarted

- name: apparmor enforce clamd
  command: /usr/sbin/aa-enforce clamd
  notify: Restart ClamAV
